name: Build & Release Winlator APK

on:
  push:
    branches:
      #- 'v*'   # 只有推送 tag 时触发，例如 v1.0.0
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1 安装依赖
        run: |
          sudo apt update && sudo apt install -y libarchive-tools wget

      - name: 2. 拉取源码（包含子模块）
        uses: actions/checkout@v4
        with:
          ref: master # 指定分支
          submodules: recursive

      - name: 3. 验证 gradle
        uses: gradle/wrapper-validation-action@v3

      - name: 4. 设置 JDK17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 5 恢复缓存
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 小插曲-查找输出文件路径
        run: ls $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/ | grep native_handle.h

      - name: 6. 构建 APK
        run: chmod +x ./gradlew && ./gradlew assembleDebug

      - name: 7. 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: Winlator-release-apk
          path: app/build/outputs/apk/debug/app-debug.apk
