name: Build & Release Winlator APK

on:
  push:
    tags:
      - '*'    # 只有推送 tag 时触发，例如 v1.0.0
    #branches:
    #  - master-10.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1 安装依赖
        run: |
          sudo apt update && sudo apt install -y libarchive-tools wget

      - name: 2. 拉取源码
        uses: actions/checkout@v4
        with:
          ref: master-10.0 # 指定分支
          lfs: true # 下载 LFS 文件
          submodules: recursive # 拉取子模块

      - name: 3. 验证 gradle
        uses: gradle/wrapper-validation-action@v3

      - name: 4. 设置 JDK17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 5 恢复缓存
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 6. 构建 APK
        run: chmod +x ./gradlew && ./gradlew assembleDebug

      - name: 7. 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: winlator-master-10.0.apk
          path: app/build/outputs/apk/debug/app-debug.apk
